### ISSUE TITLE
[ FEATURE ] Add folder structure for screens

### ISSUE THREAD

**Issue by saheelsapovadia** [clubgamma/task-tracker#1]
Welcome 🙏 

Tasks under this issue-
- [ ] 1. Create a basic folder structure at root level named "Screens"
- [ ] 2. Create two basic empty screens-
  1.  Splash screen
  2.  Tasks screen

Follow all the guidelines given in the [README.md](https://github.com/clubgamma/task-tracker/blob/main/README.md) and [CONTRIBUTING.md](https://github.com/clubgamma/task-tracker/blob/main/CONTRIBUTING.md) file 🚀

This project needs a ⭐ from you 😄 !

**Comment by Yash-Goyal007** [comment]
Please assign this issue to me..

**Comment by saheelsapovadia** [comment]
@Yash-Goyal007 Thank you for showing interest. This is a quick one, hope you enjoy!

**Comment by saheelsapovadia** [comment]
@anshrusia200 Enjoy!

**Comment by saheelsapovadia** [comment]
@anshrusia200 Okay np

**Comment by rokkoo** [comment]
Hi! if you want I can try to do it :)
